Repository tox-dev/tox, pull requests merged in 2018-07, with the labels that each got.

#871 Move to an automated release flow
  .codecov.yml
  .gitignore
  .travis.yml
  HOWTORELEASE.rst
  README.rst
  setup.cfg
  setup.py
  tasks/client_secret.json
  tasks/notify.py
  tasks/pra.sh
  tasks/pre-process-changelog.py
  tasks/release.py
  tox.ini
Labels: level:medium, needs:review, type:internal

#883 Fix PyPi description does not render #879
  .travis.yml
  CHANGELOG.rst
  changelog/879.bugfix.rst
  doc/changelog.rst
  doc/conf.py
  setup.py
  tox.ini
Labels: area:documentation, bug:minor, level:medium, needs:review

#887 CI optimization
  .travis.yml
  appveyor.yml
  doc/Makefile
Labels: level:medium, needs:review, type:internal

#910 Touch '.egg-info' directory after install (#909)
  changelog/909.bugfix.rst
  src/tox/config.py
  src/tox/venv.py
  tests/test_config.py
Labels: area:install, feature:new, needs:discussion, needs:review, pr-available

#897 Add a system overview section on the landing page #867
  changelog/867.doc.rst
  doc/_static/custom.css
  doc/img/tox_flow.png
  doc/index.rst
Labels: area:documentation, feature:new, level:easy, needs:review

#914 No longer hard-code pythons
  changelog/914.feature.rst
  src/tox/config.py
  src/tox/constants.py
Labels: area:configuration, feature:new, level:medium
