Repository tox-dev/tox, pull requests merged in 2019-11, with the labels that each got.

#1446 Use _TOX_PARALLEL_ENV environment variable to control the behavior
  docs/changelog/1444.bugfix.rst
  src/tox/_pytestplugin.py
  src/tox/config/__init__.py
  src/tox/config/parallel.py
  src/tox/session/__init__.py
  src/tox/session/commands/run/parallel.py
  src/tox/venv.py
  tests/integration/test_parallel_inception.py
  tests/unit/config/test_config.py
Labels: bot:chronographer:provided

#1401 Fix reporting exit due to (real) signal
  docs/changelog/1401.bugfix.rst
  src/tox/exception.py
  tests/unit/test_result.py
Labels: bot:chronographer:provided

#1452 Fix provisioning from pyvenv interpreter
  CONTRIBUTORS
  docs/changelog/1452.bugfix.rst
  src/tox/session/commands/provision.py
  tests/integration/test_provision_int.py
Labels: bot:chronographer:provided

#1439 Adds SSL proxy variables to default passenv
  CONTRIBUTORS
  docs/changelog/1437.bugfix.rst
  docs/config.rst
  src/tox/config/__init__.py
  tests/unit/config/test_config.py
  tox.ini
Labels: bot:chronographer:provided

#1456 fix the failing CI on master
  .pre-commit-config.yaml
  azure-pipelines.yml
  docs/changelog/1452.bugfix.rst
  docs/changelog/1456.deprecation.rst
  setup.cfg
  src/tox/exception.py
  src/tox/session/commands/provision.py
  tests/integration/test_parallel_interrupt.py
  tests/integration/test_provision_int.py
  tests/unit/config/test_config.py
  tests/unit/test_venv.py
  tox.ini
Labels: bot:chronographer:provided, enhancement

#1460 release 3.14.1
  docs/changelog.rst
  docs/changelog/1401.bugfix.rst
  docs/changelog/1429.bugfix.rst
  docs/changelog/1437.bugfix.rst
  docs/changelog/1444.bugfix.rst
  docs/changelog/1452.bugfix.rst
  docs/changelog/1456.deprecation.rst
Labels: enhancement

#1466 Fix global configuration fallback in Jenkins runs
  CONTRIBUTORS
  docs/changelog/1428.bugfix.rst
  src/tox/_pytestplugin.py
  src/tox/config/__init__.py
  tests/unit/config/test_config.py
Labels: bot:chronographer:provided
