Repository tox-dev/tox, pull requests merged in 2020-06, with the labels that each got.

#1594 Allow both pre- and post- PEP 610 outputs in test_venv_special_chars_issue252
  docs/changelog/1594.misc.rst
  tests/unit/test_z_cmdline.py
  tox.ini
Labels: bot:chronographer:provided

#1588 Add option to delay propegating SIGINT to child process
  CONTRIBUTORS
  docs/changelog/1497.bugfix.rst
  docs/config.rst
  src/tox/action.py
  src/tox/config/__init__.py
  src/tox/session/__init__.py
  src/tox/venv.py
  tests/unit/config/test_config.py
Labels: bot:chronographer:provided

#1597 PyPy 7.3.1 now generates Scripts instead of bin on Windows
  .pre-commit-config.yaml
  docs/changelog/1597.bugfix.rst
  src/tox/config/__init__.py
  src/tox/helper/get_version.py
  src/tox/interpreters/__init__.py
  src/tox/interpreters/via_path.py
  tests/unit/interpreters/test_interpreters.py
Labels: bot:chronographer:provided, enhancement

#1598 release 3.15.2
  docs/changelog.rst
  docs/changelog/1497.bugfix.rst
  docs/changelog/1594.misc.rst
  docs/changelog/1597.bugfix.rst
Labels: enhancement

#1603 Precompile common regular expressions
  CONTRIBUTORS
  docs/changelog/1603.misc.rst
  src/tox/config/__init__.py
Labels: bot:chronographer:provided

#1606 Allow true separation of environment setup and test run
  docs/changelog/1605.feature.rst
  src/tox/config/__init__.py
  tests/unit/config/test_config.py
Labels: bot:chronographer:provided, enhancement

#1607 release 3.16.0
  docs/changelog.rst
  docs/changelog/1603.misc.rst
  docs/changelog/1605.feature.rst
Labels: enhancement

#1609 🐛 Register `{temp_dir}` as a valid substitution
  docs/changelog/1609.bugfix.rst
  src/tox/config/__init__.py
Labels: bot:chronographer:provided

#1610 release 3.16.1
  docs/changelog.rst
  docs/changelog/1609.bugfix.rst
Labels: enhancement
