Repository tox-dev/tox, pull requests merged in 2020-02, with the labels that each got.

#1521 fix pypy CI failure
  azure-pipelines.yml
  docs/changelog/1521.bugfix.rst
  src/tox/session/commands/run/parallel.py
Labels: bot:chronographer:provided

#1519 Avoid incompatible six
  docs/changelog/1519.bugfix.rst
  setup.cfg
Labels: bot:chronographer:provided

#1522 release 3.14.4
  docs/changelog.rst
  docs/changelog/1493.feature.rst
  docs/changelog/1498.feature.rst
  docs/changelog/1519.bugfix.rst
  docs/changelog/1521.bugfix.rst
Labels: enhancement

#1526 Allow user to inject specific Pythons to try as step 1 during discovery
  docs/changelog/1526.feature.rst
  src/tox/config/__init__.py
  src/tox/interpreters/common.py
  src/tox/interpreters/unix.py
  src/tox/interpreters/windows/__init__.py
  tests/unit/interpreters/test_interpreters.py
Labels: bot:chronographer:provided, enhancement

#1527 release 3.14.5
  docs/changelog.rst
  docs/changelog/1526.feature.rst
Labels: enhancement
