Repository tox-dev/tox, pull requests merged in 2020-09, with the labels that each got.

#1668 Support environment files and comments in setenv
  docs/changelog/1667.feature.rst
  docs/config.rst
  src/tox/config/__init__.py
  tests/unit/config/test_config.py
Labels: bot:chronographer:provided, enhancement

#1669 release 3.20.0
  docs/changelog.rst
  docs/changelog/1636.bugfix.rst
  docs/changelog/1654.bugfix.rst
  docs/changelog/1656.bugfix.rst
  docs/changelog/1667.feature.rst
Labels: enhancement

#1682 Update constraint for importlib-metadata
  CONTRIBUTORS
  docs/changelog/1682.bugfix.rst
  setup.cfg
Labels: bot:chronographer:provided
