Repository tox-dev/tox, pull requests merged in 2020-07, with the labels that each got.

#1612 Add long --verbose/--quiet cli arguments
  CONTRIBUTORS
  docs/changelog/1612.feature.rst
  src/tox/config/reporter.py
  tests/unit/config/test_config.py
Labels: bot:chronographer:provided

#1613 Update recommended packaging information for Flit
  docs/changelog/1613.doc.rst
  docs/example/package.rst
Labels: bot:chronographer:provided

#1616 Use a HOSTNAME environment variable instead of socket.getfqdn() in ResultLog
  docs/changelog/1615.feature.rst
  src/tox/logs/result.py
  tests/unit/test_result.py
Labels: bot:chronographer:provided

#1617 release 3.17.0
  docs/changelog.rst
  docs/changelog/1612.feature.rst
  docs/changelog/1613.doc.rst
  docs/changelog/1615.feature.rst
Labels: enhancement

#1618 Fix tests when HOSTNAME is set, but empty string
  docs/changelog/1616.bugfix.rst
  tests/unit/test_result.py
Labels: bot:chronographer:provided

#1619 release 3.17.1
  docs/changelog.rst
  docs/changelog/1616.bugfix.rst
Labels: enhancement

#1601 Add alias "allowlist_externals" to "whitelist_externals"
  CONTRIBUTORS
  docs/changelog/1491.deprecation.rst
  docs/config.rst
  docs/example/basic.rst
  docs/index.rst
  src/tox/config/__init__.py
  src/tox/venv.py
  tests/integration/test_parallel_interrupt.py
  tests/unit/config/test_config.py
  tests/unit/session/test_parallel.py
  tests/unit/test_venv.py
  tests/unit/test_z_cmdline.py
Labels: bot:chronographer:provided

#1556 Fix CI
  .coveragerc
  .github/workflows/check.yml
  .pre-commit-config.yaml
  README.md
  azure-pipelines.yml
  docs/changelog/1556.bugfix.rst
  docs/changelog/examples.rst
  docs/conf.py
  setup.cfg
  src/new.md
  src/tox/config/cli/env_var.py
  src/tox/config/cli/ini.py
  src/tox/config/cli/parser.py
  src/tox/config/main.py
  src/tox/config/sets.py
  src/tox/config/source/api.py
  src/tox/config/source/ini/__init__.py
  src/tox/config/source/ini/convert.py
  src/tox/config/source/ini/factor.py
  src/tox/config/source/ini/replace.py
  src/tox/execute/local_sub_process/__init__.py
  src/tox/execute/local_sub_process/read_via_thread_windows.py
  src/tox/helper/build_isolated.py
  src/tox/log/env.py
  src/tox/log/result.py
  src/tox/plugin/spec.py
  src/tox/provision/__init__.py
  src/tox/pytest.py
  src/tox/report.py
  src/tox/session/cmd/list_env.py
  src/tox/session/cmd/run/parallel.py
  src/tox/session/cmd/run/sequential.py
  src/tox/session/cmd/show_config.py
  src/tox/session/cmd/version_flag.py
  src/tox/tox_env/api.py
  src/tox/tox_env/python/api.py
  src/tox/tox_env/python/virtual_env/package/api.py
  src/tox/tox_env/python/virtual_env/package/dev.py
  src/tox/tox_env/python/virtual_env/runner.py
  src/tox/util/graph.py
  src/tox/util/lock.py
  src/tox/util/path.py
  src/tox/util/spinner.py
  tests/conftest.py
  tests/integration/tox_env/virtual_env/test_int_setuptools.py
  tests/unit/config/cli/test_cli_ini.py
  tests/unit/config/ini/replace/conftest.py
  tests/unit/config/ini/replace/test_replace_posargs.py
  tests/unit/config/ini/replace/test_replace_tox_env.py
  tests/unit/config/test_main.py
  tests/unit/execute/bad_process.py
  tests/unit/execute/test_local_subprocess.py
  tests/unit/test_list_env.py
  tests/unit/tox_env/python/virtual_env/setuptools/package/test_wheel_build.py
  tests/unit/tox_env/test_show_config.py
  tox.ini
Labels: bot:chronographer:provided, enhancement

#1630 Color support
  docs/changelog/1630.feature.rst
  setup.cfg
  src/tox/config/cli/parse.py
  src/tox/config/cli/parser.py
  src/tox/config/source/api.py
  src/tox/config/source/ini/__init__.py
  src/tox/config/source/ini/convert.py
  src/tox/execute/api.py
  src/tox/execute/outcome.py
  src/tox/pytest.py
  src/tox/report.py
  src/tox/tox_env/api.py
  src/tox/tox_env/builder.py
  src/tox/tox_env/python/virtual_env/runner.py
  tests/unit/config/cli/test_cli_env_var.py
  tests/unit/config/cli/test_cli_ini.py
  tests/unit/config/cli/test_parser.py
  tests/unit/config/test_main.py
  tests/unit/execute/local_subprocess_sigint.py
  tests/unit/execute/test_local_subprocess.py
  tests/unit/pytest/test_init.py
  tox.ini
Labels: bot:chronographer:provided, enhancement

#1629 Fix isolated build helper scripts
  docs/changelog/1629.bugfix.rst
  src/tox/helper/build_isolated.py
  src/tox/helper/build_requires.py
  tests/unit/package/test_package.py
Labels: bot:chronographer:provided

#1632 release 3.18.1
  docs/changelog.rst
  docs/changelog/1629.bugfix.rst
Labels: enhancement

#1614 Implement support for PEP517 backend-path setting
  docs/changelog/1575.feature.rst
  src/tox/helper/build_isolated.py
  src/tox/package/builder/isolated.py
  tests/unit/package/builder/test_package_builder_isolated.py
Labels: bot:chronographer:provided

#1631 Docs grammar
  docs/changelog/1631.doc.rst
  docs/config.rst
  docs/index.rst
  docs/plugins.rst
  tests/unit/util/test_spinner.py
Labels: bot:chronographer:provided
