Repository tox-dev/tox, pull requests merged in 2020-05, with the labels that each got.

#1573 docs: Add prelude section on testenvs to config guide
  .pre-commit-config.yaml
  docs/changelog/1423.bugfix.rst
  docs/changelog/1573.doc.rst
  docs/config.rst
  tox.ini
Labels: bot:chronographer:provided

#1562 Passenv PIP_EXTRA_INDEX_URL by default
  CONTRIBUTING.rst
  CONTRIBUTORS
  docs/changelog/1561.feature.rst
  docs/config.rst
  src/tox/config/__init__.py
  tests/unit/config/test_config.py
Labels: bot:chronographer:provided

#1574 release 3.15.0
  docs/changelog.rst
  docs/changelog/1418.feature.rst
  docs/changelog/1423.bugfix.rst
  docs/changelog/1542.bugfix.rst
  docs/changelog/1544.bugfix.rst
  docs/changelog/1545.feature.rst
  docs/changelog/1547.bugfix.rst
  docs/changelog/1561.feature.rst
  docs/changelog/1573.doc.rst
Labels: enhancement

#1579 Fix CI due to latest pip output change
  tests/unit/test_z_cmdline.py
  tox.ini
Labels: bot:chronographer:provided, enhancement

#1585 Do not interpolate values from tox --showconfig
  CONTRIBUTORS
  docs/changelog/1585.bugfix.rst
  src/tox/session/commands/show_config.py
  tests/unit/session/test_show_config.py
Labels: bot:chronographer:provided

#1587 release 3.15.1
  docs/changelog.rst
  docs/changelog/1585.bugfix.rst
Labels: enhancement
