Repository tox-dev/tox, pull requests merged in 2021-09, with the labels that each got.

#2206 Let tox run fail when all envs are skipped
  docs/changelog/2195.feature.rst
  src/tox/session/cmd/run/common.py
  tests/session/cmd/test_sequential.py
Labels: bot:chronographer:provided

#2209 Make ConfigSet ABC and add contains to Loader
  .pre-commit-config.yaml
  docs/changelog/2209.bugfix.rst
  src/tox/config/loader/api.py
  src/tox/config/sets.py
  tests/config/loader/test_memory_loader.py
  tests/config/test_sets.py
Labels: bot:chronographer:provided

#2212 Fix old-new value on recreate cache miss-match are swapped
  .pre-commit-config.yaml
  docs/changelog/2211.bugfix.rst
  src/tox/pytest.py
  src/tox/tox_env/python/api.py
  tests/tox_env/python/test_python_api.py
  tests/tox_env/python/virtual_env/test_virtualenv_api.py
Labels: bot:chronographer:provided

#2214 Support for plugin before and after, fix ASCII report fails
  docs/changelog/2201.feature.rst
  docs/changelog/2213.bugfix.rst
  docs/conf.py
  docs/plugins_api.rst
  src/tox/plugin/manager.py
  src/tox/plugin/spec.py
  src/tox/pytest.py
  src/tox/report.py
  src/tox/session/cmd/run/single.py
  src/tox/util/spinner.py
  tests/plugin/test_inline.py
  whitelist.txt
Labels: bot:chronographer:provided

#2207 Only respect ALL environments when not in parallel
  docs/changelog/2167.bugfix.rst
  src/tox/config/__init__.py
  tests/unit/config/test_config_parallel.py
Labels: help:wanted, bot:chronographer:provided

#2203 venv: do not prepend a truncated shebang interpreter
  docs/changelog/2208.bugfix.rst
  docs/config.rst
  src/tox/venv.py
  tests/unit/test_venv.py
Labels: bot:chronographer:provided

#2218 Allow plugins to change pass_env and set_env
  .pre-commit-config.yaml
  docs/changelog/2215.feature.rst
  src/tox/config/set_env.py
  src/tox/config/sets.py
  src/tox/pytest.py
  src/tox/tox_env/api.py
  tests/config/test_set_env.py
  tests/plugin/test_plugin.py
Labels: bot:chronographer:provided

#2223 Support for environment files in set_env
  docs/changelog/1938.feature.rst
  docs/config.rst
  src/tox/config/loader/ini/__init__.py
  src/tox/config/set_env.py
  src/tox/config/sets.py
  src/tox/pytest.py
  src/tox/tox_env/errors.py
  tests/config/test_set_env.py
Labels: bot:chronographer:provided

#2224 Support for --no-provision flag
  docs/changelog/1951.feature.rst
  docs/conf.py
  pyproject.toml
  src/tox/__init__.py
  src/tox/journal/main.py
  src/tox/provision.py
  src/tox/session/cmd/quickstart.py
  src/tox/session/cmd/version_flag.py
  tests/config/cli/test_cli_env_var.py
  tests/config/cli/test_cli_ini.py
  tests/session/cmd/test_quickstart.py
  tests/test_provision.py
  tests/test_version.py
Labels: enhancement, bot:chronographer:provided

#2225 No pyproject.toml or setup.py and no --install-pkg assumes no package
  docs/changelog/1964.feature.rst
  src/tox/tox_env/package.py
  src/tox/tox_env/python/virtual_env/runner.py
  src/tox/tox_env/runner.py
  tests/session/cmd/test_depends.py
  tests/session/cmd/test_show_config.py
  tests/session/cmd/test_state.py
  tests/tox_env/python/virtual_env/test_package.py
Labels: enhancement, bot:chronographer:provided

#2226 Add support for TOX_LIMITED_SHEBANG
  docs/changelog/2208.feature.rst
  src/tox/execute/local_sub_process/__init__.py
  src/tox/execute/util.py
  tests/execute/local_subprocess/test_execute_util.py
  tests/execute/local_subprocess/test_local_subprocess.py
  whitelist.txt
Labels: enhancement, bot:chronographer:provided

#2234 Fix list/depends cmd creates package env as run env
  .pre-commit-config.yaml
  docs/changelog/2234.bugfix.rst
  src/tox/execute/local_sub_process/__init__.py
  src/tox/session/cmd/depends.py
  src/tox/session/cmd/list_env.py
  src/tox/session/cmd/run/common.py
  src/tox/session/state.py
  src/tox/tox_env/python/runner.py
  src/tox/tox_env/python/virtual_env/runner.py
  src/tox/tox_env/register.py
  src/tox/tox_env/runner.py
  tests/session/cmd/test_list_envs.py
  tests/session/cmd/test_show_config.py
  tests/tox_env/test_register.py
  tox.ini
Labels: enhancement, bot:chronographer:provided

#2235 Support for external packages and builders
  .github/workflows/check.yml
  docs/changelog/2204.feature.rst
  docs/config.rst
  src/tox/execute/pep517_backend.py
  src/tox/plugin/manager.py
  src/tox/pytest.py
  src/tox/session/cmd/run/single.py
  src/tox/session/state.py
  src/tox/tox_env/api.py
  src/tox/tox_env/package.py
  src/tox/tox_env/python/package.py
  src/tox/tox_env/python/pip/pip_install.py
  src/tox/tox_env/python/pip/req/file.py
  src/tox/tox_env/python/pip/req_file.py
  src/tox/tox_env/python/runner.py
  src/tox/tox_env/python/virtual_env/api.py
  src/tox/tox_env/python/virtual_env/package/cmd_builder.py
  src/tox/tox_env/python/virtual_env/package/pep517.py
  src/tox/tox_env/python/virtual_env/package/util.py
  src/tox/tox_env/python/virtual_env/runner.py
  src/tox/tox_env/runner.py
  src/tox/util/pep517/frontend.py
  tests/conftest.py
  tests/test_provision.py
  tests/tox_env/python/pip/req/test_file.py
  tests/tox_env/python/pip/test_pip_install.py
  tests/tox_env/python/virtual_env/package/__init__.py
  tests/tox_env/python/virtual_env/package/conftest.py
  tests/tox_env/python/virtual_env/package/test_package_cmd_builder.py
  tests/tox_env/python/virtual_env/package/test_package_pep517.py
  tests/tox_env/python/virtual_env/package/test_python_package_util.py
  tests/tox_env/python/virtual_env/test_package.py
  tests/tox_env/python/virtual_env/test_setuptools.py
  tests/tox_env/python/virtual_env/test_virtualenv_api.py
  whitelist.txt
Labels: enhancement, bot:chronographer:provided
