Repository tox-dev/tox, pull requests merged in 2021-08, with the labels that each got.

#2134 Add support for allowlist_externals
  docs/changelog/1127.feature.rst
  docs/config.rst
  docs/user_guide.rst
  setup.cfg
  src/tox/execute/local_sub_process/__init__.py
  src/tox/execute/request.py
  src/tox/tox_env/api.py
  src/tox/util/spinner.py
  tests/conftest.py
  tests/execute/local_subprocess/test_local_subprocess.py
  tests/execute/test_request.py
  tests/tox_env/test_tox_env_api.py
  whitelist.txt
Labels: bot:chronographer:provided

#2138 Add support for os path separator substitution in ini files
  .pre-commit-config.yaml
  docs/changelog/2125.feature.rst
  src/tox/config/loader/ini/replace.py
  tests/config/loader/ini/replace/test_replace_os_pathsep.py
Labels: bot:chronographer:provided

#2139 Add envlogdir support
  docs/changelog/2123.feature.rst
  docs/config.rst
  src/tox/tox_env/api.py
  tests/tox_env/test_tox_env_api.py
Labels: bot:chronographer:provided

#2140 When cleaning dirs clean only their content
  docs/changelog/2139.feature.rst
  src/tox/config/source/legacy_toml.py
  src/tox/tox_env/api.py
  src/tox/util/path.py
  src/tox/util/pep517/frontend.py
  tests/util/test_path.py
Labels: enhancement, bot:chronographer:provided

#2141 Do not fail when commands do not parse with shlex
  docs/changelog/1944.bugfix.rst
  src/tox/config/loader/str_convert.py
  tests/config/loader/test_str_convert.py
  whitelist.txt
Labels: bug:normal, bot:chronographer:provided

#2144 Add outcome of the tox environment evaluation into result JSON
  docs/changelog/1405.feature.rst
  src/tox/session/cmd/run/common.py
  tests/session/cmd/test_sequential.py
Labels: enhancement, bot:chronographer:provided

#2145 Support all Unix shell-style wildcards for pass_env
  docs/changelog/2121.feature.rst
  docs/config.rst
  src/tox/tox_env/api.py
  tests/tox_env/test_tox_env_api.py
  whitelist.txt
Labels: enhancement, bot:chronographer:provided

#2142 Add support for exec subcommand
  docs/changelog/1790.feature.rst
  src/tox/plugin/manager.py
  src/tox/session/cmd/devenv.py
  src/tox/session/cmd/exec_.py
  src/tox/session/common.py
  tests/config/cli/conftest.py
  tests/session/cmd/test_exec_.py
  whitelist.txt
Labels: enhancement, bot:chronographer:provided

#2146 Suport # character in path of tox project
  docs/changelog/763.bugfix.rst
  src/tox/config/loader/ini/__init__.py
  src/tox/config/loader/ini/replace.py
  src/tox/config/loader/str_convert.py
  src/tox/config/set_env.py
  src/tox/pytest.py
  tests/session/cmd/test_show_config.py
  whitelist.txt
Labels: bug:normal, bot:chronographer:provided

#2147 Fix virtual environment creation not cached
  docs/changelog/2041.bugfix.rst
  src/tox/tox_env/info.py
  tests/session/cmd/test_sequential.py
Labels: bug:normal, bot:chronographer:provided

#2150 Support CLI run flags for tox config
  docs/changelog/2037.bugfix.rst
  src/tox/provision.py
  src/tox/session/cmd/run/common.py
  src/tox/session/cmd/run/single.py
  src/tox/session/cmd/show_config.py
  src/tox/tox_env/api.py
  src/tox/tox_env/package.py
  src/tox/tox_env/runner.py
  tests/session/cmd/test_show_config.py
Labels: bug:normal, bot:chronographer:provided

#2151 Clarify documentation for --runner
  docs/changelog/2004.doc.rst
  docs/cli_interface.rst
  src/tox/config/cli/parse.py
  src/tox/session/state.py
Labels: area:documentation, bot:chronographer:provided

#2152 Document package python requires differing from tox
  docs/changelog/1975.doc.rst
  docs/config.rst
Labels: area:documentation, bot:chronographer:provided

#2153 Note constraint files are a subset of requirement files
  docs/changelog/1939.doc.rst
  docs/faq.rst
Labels: area:documentation, bot:chronographer:provided

#2157 Add support for args_are_paths
  docs/changelog/2122.feature.rst
  docs/config.rst
  src/tox/config/loader/ini/replace.py
  src/tox/config/main.py
  src/tox/pytest.py
  src/tox/session/cmd/exec_.py
  src/tox/tox_env/runner.py
  tests/config/test_main.py
  tests/session/cmd/test_exec_.py
Labels: enhancement, bot:chronographer:provided

#2156 Check base python against env name and raise if differs
  docs/changelog.rst
  docs/changelog/1840.feature.rst
  docs/changelog/1975.doc.rst
  docs/config.rst
  src/tox/tox_env/python/api.py
  src/tox/tox_env/python/virtual_env/api.py
  tests/tox_env/python/test_python_api.py
Labels: enhancement, bot:chronographer:provided

#2158 Add support for execute interrupt timeouts
  docs/changelog/2124.bugfix.rst
  docs/config.rst
  src/tox/execute/api.py
  src/tox/execute/local_sub_process/__init__.py
  src/tox/execute/pep517_backend.py
  src/tox/pytest.py
  src/tox/tox_env/api.py
  tests/execute/local_subprocess/local_subprocess_sigint.py
  tests/execute/local_subprocess/test_local_subprocess.py
  tests/session/cmd/test_show_config.py
  whitelist.txt
Labels: enhancement, bot:chronographer:provided

#2162 Add LC_ALL to implicit tox passenv
  docs/changelog/2162.bugfix.rst
  src/tox/config/__init__.py
Labels: bot:chronographer:provided

#2161 Fix parallel show output not working
  docs/changelog/2161.bugfix.rst
  src/tox/session/cmd/run/common.py
  tests/session/cmd/test_parallel.py
Labels: bot:chronographer:provided

#2168 📝 Make Sphinx strict about broken references
  .readthedocs.yml
  docs/changelog.rst
  docs/changelog/2168.misc.rst
  docs/conf.py
  docs/example/basic.rst
  docs/index.rst
  tox.ini
Labels: bot:chronographer:provided

#2164 ASCII output for --parallel report lines
  CONTRIBUTORS
  docs/changelog/1421.bugfix.rst
  src/tox/util/spinner.py
  tests/unit/util/test_spinner.py
Labels: bot:chronographer:provided

#2172 Internal changes to accomodate tox-conda
  docs/changelog/2172.feature.rst
  src/tox/session/state.py
  src/tox/tox_env/api.py
  src/tox/tox_env/package.py
  src/tox/tox_env/python/api.py
  src/tox/tox_env/python/pip/pip_install.py
  src/tox/tox_env/python/runner.py
  src/tox/tox_env/python/virtual_env/api.py
  src/tox/tox_env/python/virtual_env/package/api.py
  src/tox/tox_env/runner.py
  tests/conftest.py
Labels: enhancement, bot:chronographer:provided

#2174 release 3.24.3
  docs/changelog.rst
  docs/changelog/1421.bugfix.rst
  docs/changelog/2168.misc.rst
Labels: enhancement, bot:chronographer:skip

#2173 release 4.0.0a8
  docs/changelog.rst
  docs/changelog/1127.feature.rst
  docs/changelog/1405.feature.rst
  docs/changelog/1790.feature.rst
  docs/changelog/1840.feature.rst
  docs/changelog/1939.doc.rst
  docs/changelog/1944.bugfix.rst
  docs/changelog/1975.doc.rst
  docs/changelog/2004.doc.rst
  docs/changelog/2037.bugfix.rst
  docs/changelog/2041.bugfix.rst
  docs/changelog/2121.feature.rst
  docs/changelog/2122.feature.rst
  docs/changelog/2123.feature.rst
  docs/changelog/2124.bugfix.rst
  docs/changelog/2125.feature.rst
  docs/changelog/2139.feature.rst
  docs/changelog/2161.bugfix.rst
  docs/changelog/2172.feature.rst
  docs/changelog/763.bugfix.rst
Labels: enhancement, bot:chronographer:skip

#2175 📝 Document when `temp_dir` setting and substitutions appeared
  docs/config.rst
Labels: bot:chronographer:skip

#2178 🐛📝 Suppress epub unknown MIME warnings
  docs/conf.py
Labels: bot:chronographer:skip

#2180 Improve documentation and try furo
  docs/_static/custom.css
  docs/changelog/1881.doc.rst
  docs/conf.py
  docs/config.rst
  docs/development.rst
  docs/img/overview.mermaidjs
  docs/img/overview_dark.svg
  docs/img/overview_light.svg
  docs/img/tox_flow.png
  docs/index.rst
  docs/installation.rst
  docs/plugins.rst
  docs/plugins_api.rst
  docs/user_guide.rst
  setup.cfg
Labels: area:documentation, bot:chronographer:provided

#2181 fix spelling of PyPI
  .github/workflows/check.yml
  docs/installation.rst
  docs/plugins.rst
  src/tox/pytest.py
Labels: bot:chronographer:skip

#2191 Internal changes to support tox-gh-actions
  docs/changelog/2191.bugfix.rst
  docs/changelog/2191.feature.rst
  src/tox/config/loader/api.py
  src/tox/config/loader/ini/__init__.py
  src/tox/config/loader/memory.py
  src/tox/config/main.py
  src/tox/config/of_type.py
  src/tox/config/sets.py
  src/tox/config/source/api.py
  src/tox/config/source/ini.py
  src/tox/plugin/manager.py
  tests/config/loader/ini/replace/conftest.py
  tests/config/test_of_types.py
  tests/config/test_sets.py
  whitelist.txt
Labels: bot:chronographer:provided
