Repository tox-dev/tox, pull requests merged in 2022-12, with the labels that each got.

#2574 Avoid recreation of virtualenv due to symlinks
  docs/changelog/2574.bugfix.rst
  src/tox/tox_env/python/virtual_env/api.py
Labels: bug:minor, bot:chronographer:provided

#2577 Add missing build test dependency
  docs/changelog/2576.bugfix.rst
  pyproject.toml
  tox.ini
Labels: bot:chronographer:provided

#2579 Support for recursive extras
  .pre-commit-config.yaml
  docs/changelog/2567.feature.rst
  pyproject.toml
  src/tox/tox_env/python/virtual_env/package/cmd_builder.py
  src/tox/tox_env/python/virtual_env/package/pyproject.py
  src/tox/tox_env/python/virtual_env/package/util.py
  tests/tox_env/python/virtual_env/package/test_python_package_util.py
  tox.ini
Labels: bot:chronographer:provided

#2580 Do not set COLUMNS or LINES if already set by user
  docs/changelog/2575.bugfix.rst
  src/tox/execute/local_sub_process/__init__.py
  tests/execute/local_subprocess/test_local_subprocess.py
Labels: bot:chronographer:provided

#2581 Allow replacing keys with - in INI config
  docs/changelog/2569.bugfix.rst
  src/tox/config/loader/ini/replace.py
  tests/config/loader/ini/replace/test_replace_tox_env.py
Labels: bot:chronographer:provided

#2582 Use devpi-process instead rolling our own
  pyproject.toml
  src/tox/pytest.py
  tests/test_provision.py
Labels: bot:chronographer:skip

#2585 Update bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: bot:chronographer:skip

#2586 Support - prefix for commands exit code ignore
  docs/changelog/2561.bugfix.rst
  src/tox/config/loader/str_convert.py
  tests/session/cmd/test_sequential.py
Labels: bot:chronographer:provided

#2587 Ensure paths constructed by tox stay meaningful
  docs/changelog/2562.bugfix.rst
  src/tox/config/main.py
  tests/config/test_main.py
Labels: bot:chronographer:provided

#2588 Ensure only one tox environment operates on a packaging environment
  docs/changelog/2564.bugfix.rst
  src/tox/tox_env/package.py
  whitelist.txt
Labels: bot:chronographer:provided

#2589 Do not pull in Python 2 as dependency
  .github/workflows/check.yml
  tests/tox_env/python/virtual_env/test_virtualenv_api.py
Labels: bot:chronographer:skip

#2593 Lock parallel package operations
  .pre-commit-config.yaml
  docs/changelog/2594.bugfix.rst
  pyproject.toml
  src/tox/tox_env/api.py
  src/tox/tox_env/package.py
  src/tox/util/path.py
Labels: bot:chronographer:provided

#2597 Better handling of build backend without editable support and add --exit-and-dump-after flag
  docs/changelog/2595.bugfix.rst
  docs/changelog/2595.feature.rst
  pyproject.toml
  src/tox/config/cli/parser.py
  src/tox/execute/pep517_backend.py
  src/tox/run.py
  src/tox/tox_env/package.py
  src/tox/tox_env/python/api.py
  src/tox/tox_env/python/package.py
  src/tox/tox_env/python/virtual_env/package/pyproject.py
  tests/config/cli/test_cli_env_var.py
  tests/config/cli/test_cli_ini.py
  tests/tox_env/python/test_python_api.py
  tests/tox_env/python/virtual_env/package/test_package_pyproject.py
  whitelist.txt
Labels: bot:chronographer:provided

#2601 Create a FAQ entry about tox v3 - v4 compatibility
  README.md
  docs/changelog/2587.doc.rst
  docs/changelog/2602.doc.rst
  docs/changelog/2608.bugfix.rst
  docs/cli_interface.rst
  docs/config.rst
  docs/faq.rst
  docs/index.rst
  src/new.md
  src/tox/config/sets.py
Labels: bot:chronographer:skip

#2613 Default tox min_version to 4.0 instead of current tox version
  docs/changelog/2613.bugfix.rst
  src/tox/provision.py
  tests/test_provision.py
Labels: bot:chronographer:provided

#2614 Create session views of the build wheel/sdist into temp_dir
  .pre-commit-config.yaml
  docs/changelog/2612.bugfix.rst
  docs/config.rst
  pyproject.toml
  src/tox/config/sets.py
  src/tox/tox_env/python/virtual_env/package/pyproject.py
  src/tox/tox_env/python/virtual_env/package/util.py
  src/tox/util/file_view.py
  tests/tox_env/python/test_python_runner.py
  tox.ini
  whitelist.txt
Labels: bot:chronographer:provided

#2625 tox --showconfig -e py shows core configs
  docs/changelog/2624.bugfix.rst
  src/tox/session/cmd/legacy.py
  src/tox/session/env_select.py
  tests/session/cmd/test_legacy.py
Labels: bot:chronographer:provided

#2626 Unescaped comma in substitution should not be replaced during INI expansion
  docs/changelog/2616.bugfix.rst
  src/tox/config/loader/ini/replace.py
  tests/config/loader/ini/test_factor.py
Labels: bot:chronographer:provided

#2621 Document necessity to escape `#` sign used in `commands`
  docs/changelog/2615.doc.rst
  docs/changelog/2617.doc.rst
  docs/faq.rst
Labels: bot:chronographer:provided

#2643 Ensure change_dir is created before running commands
  docs/changelog/2620.bugfix.rst
  src/tox/session/cmd/run/single.py
  tests/tox_env/test_tox_env_api.py
Labels: bot:chronographer:provided

#2644 Show host python under core section as constant
  docs/changelog/2630.bugfix.rst
  src/tox/config/sets.py
  tests/session/cmd/test_show_config.py
Labels: bot:chronographer:provided

#2656 Do not log distlib.util or filelock
  .pre-commit-config.yaml
  docs/changelog/2655.bugfix.rst
  src/tox/report.py
  tests/config/cli/test_parse.py
  tests/test_report.py
Labels: bot:chronographer:provided

#2652 Document that `-v` adds debug info to `--showconfig` and `--help-ini``
  docs/changelog/2622.doc.rst
  docs/faq.rst
Labels: bot:chronographer:provided

#2666 Add repr() calls to "invalid value" exception message in StrConverter.to_bool
  docs/changelog/2665.bugfix.rst
  src/tox/config/loader/str_convert.py
  tests/config/test_sets.py
Labels: bot:chronographer:provided

#2668 Normalize extra names passed in
  docs/changelog/2655.bugfix.rst
  src/tox/tox_env/python/runner.py
  tests/tox_env/python/test_python_runner.py
Labels: bot:chronographer:provided

#2673 Fix the description of 'package' option
  docs/config.rst
Labels: bot:chronographer:skip

#2671 Fail on blanks in passed env vars
  docs/changelog/2658.feature.rst
  src/tox/tox_env/api.py
  tests/tox_env/test_tox_env_api.py
Labels: bot:chronographer:provided

#2678 Support for --no-deps within deps
  docs/changelog/2674.bugfix.rst
  src/tox/tox_env/python/pip/pip_install.py
  src/tox/tox_env/python/pip/req/file.py
  src/tox/tox_env/python/pip/req_file.py
  tests/tox_env/python/pip/test_req_file.py
Labels: bot:chronographer:provided

#2683 Fix requirements.txt parsing
  docs/changelog/2682.bugfix.rst
  src/tox/tox_env/python/pip/req_file.py
  tests/tox_env/python/pip/test_req_file.py
Labels: bot:chronographer:provided

#2700 Add PKG_CONFIG_PATH to default passenv
  docs/changelog/2700.feature.rst
  src/tox/tox_env/python/api.py
  tests/session/cmd/test_show_config.py
Labels: bot:chronographer:provided

#2709 Fix default verbosity in help
  docs/changelog/2707.bugfix.rst
  src/tox/config/cli/parser.py
Labels: bot:chronographer:provided

#2716 Add py_dot_ver and py_impl
  docs/changelog/2640.feature.rst
  docs/faq.rst
  src/tox/tox_env/api.py
  src/tox/tox_env/python/api.py
  tests/session/cmd/test_show_config.py
Labels: bot:chronographer:provided

#2714 tox3: Support provision of tox 4 with the min_version option
  .github/workflows/check.yml
  docs/changelog/2661.feature.rst
  docs/config.rst
  src/tox/config/__init__.py
  tests/integration/test_provision_int.py
  tests/unit/session/test_parallel.py
  tests/unit/session/test_provision.py
  tox.ini
Labels: bot:chronographer:provided

#2726 Show only default env list for tox config by default
  docs/changelog/2726.bugfix.rst
  src/tox/session/cmd/show_config.py
  tests/config/test_main.py
  tests/session/cmd/test_show_config.py
  tests/tox_env/test_tox_env_api.py
Labels: bot:chronographer:provided

#2727 NO_COLOR follows no-color.org logic instead of tox boolean
  docs/changelog/2719.feature.rst
  src/tox/config/cli/parser.py
  tests/config/cli/test_parser.py
Labels: bot:chronographer:provided

#2707 Restore TOX_SKIP_ENV filtering
  docs/changelog/2698.bugfix.rst
  src/tox/session/env_select.py
  tests/config/cli/test_cli_env_var.py
  tests/config/cli/test_cli_ini.py
  tests/session/test_env_select.py
Labels: bot:chronographer:provided

#2731 Fix legacy flags, deprecate them and remove --index-url
  docs/changelog/2690.bugfix.rst
  docs/faq.rst
  src/tox/session/cmd/legacy.py
  src/tox/tox_env/python/virtual_env/api.py
  tests/config/cli/test_cli_env_var.py
  tests/session/cmd/test_legacy.py
  tests/util/test_spinner.py
Labels: bot:chronographer:provided

#2711 implement pseudo tty on stdout/stderr
  docs/changelog/1773.bugfix.rst
  src/tox/execute/local_sub_process/__init__.py
  src/tox/execute/stream.py
  tests/execute/local_subprocess/test_local_subprocess.py
  whitelist.txt
Labels: bot:chronographer:provided

#2739 Fix python hash seed not being set
  docs/changelog/2645.bugfix.rst
  src/tox/session/cmd/run/common.py
  src/tox/tox_env/python/api.py
  tests/config/cli/test_cli_env_var.py
  tests/config/cli/test_cli_ini.py
  tests/config/test_set_env.py
  tests/tox_env/python/test_python_api.py
  tox.ini
Labels: bot:chronographer:provided

#2742 Fix plain section shadows env config
  .pre-commit-config.yaml
  docs/changelog/2636.bugfix.rst
  pyproject.toml
  src/tox/config/source/ini.py
  src/tox/tox_env/python/virtual_env/package/cmd_builder.py
  tests/session/cmd/test_show_config.py
  tests/test_provision.py
  tests/tox_env/python/virtual_env/package/test_python_package_util.py
  tox.ini
Labels: bot:chronographer:provided

#2744 Fix space not accepted in factor filter expression
  docs/changelog/2718.bugfix.rst
  src/tox/config/loader/ini/factor.py
  tests/config/loader/ini/replace/test_replace_posargs.py
  tests/config/loader/ini/test_factor.py
  tests/session/cmd/test_list_envs.py
Labels: bot:chronographer:provided

#2748 Ignore non-test section names and invalid factor filters
  docs/changelog/2746.bugfix.rst
  src/tox/config/loader/ini/factor.py
  src/tox/config/source/ini.py
  tests/config/source/test_source_ini.py
Labels: bot:chronographer:provided

#2751 test_sequential: resolve() the system_executable
  docs/changelog/2720.bugfix.rst
  tests/session/cmd/test_sequential.py
Labels: bot:chronographer:provided

#2757 Fix complex negative factor filters not working
  docs/changelog/2634.bugfix.rst
  docs/changelog/2720.bugfix.rst
  docs/changelog/2747.bugfix.rst
  src/tox/config/loader/ini/factor.py
  tests/config/loader/ini/test_factor.py
Labels: bot:chronographer:provided

#2761 Fix change_dir is not always relative to tox_root
  .pre-commit-config.yaml
  docs/changelog/2619.bugfix.rst
  pyproject.toml
  src/tox/tox_env/python/virtual_env/package/cmd_builder.py
  src/tox/tox_env/runner.py
  src/tox/tox_env/util.py
  tests/tox_env/test_tox_env_api.py
Labels: bot:chronographer:provided

#2774 Suppress a report output when verbosity = 0.
  docs/changelog/2697.feature.rst
  src/tox/session/cmd/run/common.py
  tests/session/cmd/run/test_common.py
Labels: bot:chronographer:provided

#2775 Fix --sdistonly behaviour
  docs/changelog/2653.bugfix.rst
  src/tox/session/cmd/run/common.py
  src/tox/tox_env/runner.py
  tests/tox_env/test_tox_env_runner.py
Labels: bot:chronographer:provided

#2776 Override toxworkdir with --workdir.
  docs/changelog/2654.bugfix.rst
  src/tox/config/sets.py
  tests/config/test_sets.py
Labels: bot:chronographer:provided

#2779 Handle whitespace around requirements
  .pre-commit-config.yaml
  docs/changelog/2773.bugfix.rst
  pyproject.toml
  src/tox/tox_env/python/pip/req/file.py
  tests/tox_env/python/pip/req/test_file.py
  tox.ini
Labels: bot:chronographer:provided

#2781 Create temp_dir if not exists
  docs/changelog/2770.bugfix.rst
  docs/config.rst
  src/tox/tox_env/api.py
  tests/tox_env/test_api.py
Labels: bot:chronographer:provided

#2785 docs(config): Fix minor typo
  docs/config.rst
Labels: bot:chronographer:skip

#2787 Update user_guide.rst
  docs/changelog/2787.doc.rst
  docs/user_guide.rst
Labels: bot:chronographer:provided

#2786 Improved factor selection to allow multiple uses of `-f` for "OR" and to allow hyphenated factors
  docs/changelog/2766.feature.rst
  src/tox/session/env_select.py
  tests/session/test_env_select.py
Labels: bot:chronographer:provided

#2789 Add faq entry about re-use of environments
  docs/changelog/2788.doc.rst
  docs/faq.rst
Labels: bot:chronographer:provided

#2790 Fix logging error with emoji in git branch name.
  docs/changelog/2768.bugfix.rst
  src/tox/pytest.py
  src/tox/tox_env/api.py
  tests/tox_env/test_tox_env_api.py
Labels: bot:chronographer:provided

#2793 Fix --skip-missing-interpreters
  docs/changelog/2649.bugfix.rst
  src/tox/session/cmd/run/single.py
  src/tox/tox_env/python/runner.py
  tests/tox_env/python/test_python_runner.py
Labels: bot:chronographer:provided

#2794 Show installed packages after setup in CI envs
  docs/changelog/2685.bugfix.rst
  pyproject.toml
  src/tox/tox_env/python/api.py
  src/tox/tox_env/python/pip/pip_install.py
  src/tox/util/ci.py
  tests/tox_env/python/test_python_api.py
  tests/tox_env/test_api.py
  tests/tox_env/test_tox_env_runner.py
  tests/util/test_ci.py
  tox.ini
  whitelist.txt
Labels: bot:chronographer:provided

#2792 Fix extracting extras from markers with many extras
  docs/changelog/2791.bugfix.rst
  src/tox/tox_env/python/virtual_env/package/util.py
  tests/tox_env/python/virtual_env/package/test_python_package_util.py
Labels: bot:chronographer:provided

#2796 Relax test_list_installed_deps() to allow other packages
  docs/changelog/2796.misc.rst
  tests/tox_env/python/test_python_api.py
Labels: bot:chronographer:provided

#2797 Skip time-machine dep and spinner tests on PyPy
  docs/changelog/2797.misc.rst
  pyproject.toml
  tests/conftest.py
Labels: bot:chronographer:provided
