Repository tox-dev/tox, pull requests merged in 2022-11, with the labels that each got.

#2529 Fix PYTHONPATH passed to envreport / "pip freeze"
  CONTRIBUTORS
  docs/changelog/2528.bugfix.rst
  src/tox/venv.py
  tests/unit/test_venv.py
Labels: bot:chronographer:provided

#2545 Avoid ignored explicit argument 're' console message
  docs/changelog/2342.bugfix.rst
  docs/faq.rst
  src/tox/config/cli/parse.py
Labels: bug:minor, bot:chronographer:provided

#2547 PythonDeps: move `cli_only` handling logic to `_parse_requirements`
  docs/changelog/2373.bugfix.rst
  src/tox/tox_env/python/pip/req/args.py
  src/tox/tox_env/python/pip/req/file.py
  src/tox/tox_env/python/pip/req_file.py
  tests/tox_env/python/pip/test_req_file.py
Labels: bot:chronographer:provided

#2546 Improve coloring of logged commands
  docs/changelog/2356.feature.rst
  src/tox/report.py
  tests/test_report.py
Labels: feature:change, bot:chronographer:provided

#2551 Bump dependencies
  .pre-commit-config.yaml
  pyproject.toml
Labels: bot:chronographer:skip

#2549 Avoid impossible minversion requirement
  docs/changelog/2414.bugfix.rst
  src/tox/provision.py
  tests/test_provision.py
  whitelist.txt
Labels: bug:minor, bot:chronographer:provided

#2502 PEP-660 support
  .gitignore
  docs/changelog/2502.feature.rst
  src/tox/tox_env/python/package.py
  src/tox/tox_env/python/pip/pip_install.py
  src/tox/tox_env/python/runner.py
  src/tox/tox_env/python/virtual_env/package/cmd_builder.py
  src/tox/tox_env/python/virtual_env/package/pyproject.py
  tests/demo_pkg_setuptools/pyproject.toml
  tests/session/cmd/test_sequential.py
  tests/session/cmd/test_show_config.py
  tests/tox_env/python/virtual_env/package/test_package_pyproject.py
Labels: bot:chronographer:provided

#2550 Allow passing config directory without filename
  docs/changelog/2340.bugfix.rst
  docs/config.rst
  src/tox/config/cli/parser.py
  src/tox/config/source/discover.py
  tests/config/cli/test_cli_ini.py
Labels: bug:minor, bot:chronographer:provided

#2557 Support for generative section names
  docs/changelog/2362.feature.rst
  docs/user_guide.rst
  src/tox/config/loader/ini/__init__.py
  src/tox/config/source/ini.py
  src/tox/config/source/ini_section.py
  tests/config/loader/ini/test_factor.py
  tests/config/test_main.py
  tests/plugin/test_plugin.py
Labels: bot:chronographer:provided

#2554 Allow installing relative paths that go outside tox root folder
  docs/changelog/2366.bugfix.rst
  src/tox/tox_env/python/pip/req/file.py
  tests/tox_env/python/pip/req/test_file.py
  tests/tox_env/python/pip/test_req_file.py
Labels: bot:chronographer:provided
