Repository tox-dev/tox, pull requests merged in 2024-11, with the labels that each got.

#3434 Pass nix-ld related variables by default in pass_env (fixes #3425)
  docs/changelog/3425.doc.rst
  docs/config.rst
  src/tox/tox_env/api.py
  tests/session/cmd/test_show_config.py
Labels: bot:chronographer:provided

#3450 Display exception name when subprocesses raise them
  docs/changelog/3450.bugfix.rst
  src/tox/execute/local_sub_process/__init__.py
  tests/execute/local_subprocess/test_local_subprocess.py
Labels: bug:minor, bot:chronographer:provided

#3452 Fix the CI after setuptools 75.6 change
  .pre-commit-config.yaml
  pyproject.toml
  src/tox/execute/api.py
  src/tox/session/cmd/run/parallel.py
  tests/execute/local_subprocess/test_local_subprocess.py
  tests/tox_env/python/virtual_env/package/test_python_package_util.py
  tox.toml
Labels: bot:chronographer:skip
